CREATE TABLE fhem.f_t_climate (
    TIMESTAMP TIMESTAMP,
    YEAR SMALLINT,
    MONTH TINYINT,
    WEEK TINYINT,
    DAY TINYINT,
    DEVICE varchar(64),
    TYPE varchar(64),
    READING varchar(64),
    VALUE DOUBLE,
    _CREATED_AT TIMESTAMP,
    PRIMARY KEY (TIMESTAMP, DEVICE, READING, VALUE),
    INDEX Search_Idx (DEVICE, READING, TIMESTAMP, VALUE),
    INDEX Report_Idx (TIMESTAMP, READING) USING BTREE,
    INDEX Date_Idx (YEAR, MONTH, DAY),
    INDEX Week_Idx (YEAR, WEEK)
);