CREATE TABLE IF NOT EXISTS fhem.d_t_gas_station (
    ID TINYINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    STATION_ID varchar(50) UNIQUE,
    BRAND varchar(64),
    STREET varchar(64),
    HOUSE_NUMBER varchar(10),
    POST_CODE INTEGER,
    PLACE varchar(64),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    REF_LOC varchar(64),
    _CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);
