CREATE TABLE IF NOT EXISTS fhem.f_t_gas_price (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TIMESTAMP TIMESTAMP,
    YEAR SMALLINT GENERATED ALWAYS AS (YEAR(TIMESTAMP)) STORED,
    MONTH TINYINT GENERATED ALWAYS AS (MONTH(TIMESTAMP)) STORED,
    WEEK TINYINT GENERATED ALWAYS AS (WEEKOFYEAR(TIMESTAMP)) STORED,
    DAY TINYINT GENERATED ALWAYS AS (DAY(TIMESTAMP)) STORED,
    FK_STATION_ID INT,
    e5 DOUBLE,
    e10 DOUBLE,
    diesel DOUBLE,
    INDEX Search_Idx (TIMESTAMP, FK_STATION_ID),
    INDEX Date_Idx (YEAR, MONTH, DAY),
    INDEX Week_Idx (YEAR, WEEK)
);