CREATE TABLE fhem.f_t_gas_price (
    ID BIGINT,
    TIMESTAMP TIMESTAMP,
    YEAR SMALLINT,
    MONTH TINYINT,
    WEEK TINYINT,
    DAY TINYINT,
    FK_STATION_ID INT,
    e5 DECIMAL,
    e10 DECIMAL,
    diesel DECIMAL,
    _CREATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    INDEX Search_Idx (TIMESTAMP, FK_STATION_ID),
    INDEX Date_Idx (YEAR, MONTH, DAY),
    INDEX Week_Idx (YEAR, WEEK)
);