CREATE TABLE fhem.history (
    TIMESTAMP TIMESTAMP,
    YEAR SMALLINT GENERATED ALWAYS AS (YEAR(TIMESTAMP)) STORED,
    MONTH TINYINT GENERATED ALWAYS AS (MONTH(TIMESTAMP)) STORED,
    WEEK TINYINT GENERATED ALWAYS AS (WEEKOFYEAR(TIMESTAMP)) STORED,
    DAY TINYINT GENERATED ALWAYS AS (DAY(TIMESTAMP)) STORED,
    DEVICE varchar(64),
    TYPE varchar(64),
    EVENT varchar(512),
    READING varchar(64),
    VALUE varchar(255),
    UNIT varchar(32),
    PRIMARY KEY (TIMESTAMP, DEVICE, READING, VALUE),
    INDEX Search_Idx (DEVICE, READING, TIMESTAMP, VALUE),
    INDEX Report_Idx (TIMESTAMP, READING) USING BTREE,
    INDEX Date_Idx (YEAR, MONTH, DAY),
    INDEX Week_Idx (YEAR, WEEK)
);